"""dropped two columns from dataelements

Revision ID: 0d70855fe2a1
Revises: 4b4d54c96500
Create Date: 2026-03-16 11:03:29.241930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d70855fe2a1'
down_revision: Union[str, Sequence[str], None] = '4b4d54c96500'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataelements', schema=None) as batch_op:
        batch_op.drop_column('referenceTableName')
        batch_op.drop_column('referenceColumnName')

    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.create_unique_constraint('UQ_Datasets', ['name', 'sourceSystemId'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_constraint('UQ_Datasets', type_='unique')

    with op.batch_alter_table('dataelements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referenceColumnName', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('referenceTableName', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
