"""database setup

Revision ID: efb5de449e26
Revises: 
Create Date: 2026-03-17 13:36:14.188890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efb5de449e26'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sourcesystems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owningApplication', sa.String(), nullable=False),
    sa.Column('createdOn', sa.DateTime(), nullable=False),
    sa.Column('createdBy', sa.String(), nullable=False),
    sa.Column('updatedOn', sa.DateTime(), nullable=False),
    sa.Column('updatedBy', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'owningApplication', name='UQ_SourceSystem')
    )
    op.create_table('datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('sourceSystemId', sa.Integer(), nullable=True),
    sa.Column('createdOn', sa.DateTime(), nullable=False),
    sa.Column('createdBy', sa.String(), nullable=False),
    sa.Column('updatedOn', sa.DateTime(), nullable=False),
    sa.Column('updatedBy', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['sourceSystemId'], ['sourcesystems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'sourceSystemId', name='UQ_Datasets')
    )
    op.create_table('dataelements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('datatype', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('datasetId', sa.Integer(), nullable=True),
    sa.Column('pii', sa.Boolean(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.Column('isPrimary', sa.Boolean(), nullable=True),
    sa.Column('isUnique', sa.Boolean(), nullable=True),
    sa.Column('isNullable', sa.Boolean(), nullable=True),
    sa.Column('createdOn', sa.DateTime(), nullable=False),
    sa.Column('createdBy', sa.String(), nullable=False),
    sa.Column('updatedOn', sa.DateTime(), nullable=False),
    sa.Column('updatedBy', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['datasetId'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'datasetId', name='UQ_Dataelements')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dataelements')
    op.drop_table('datasets')
    op.drop_table('sourcesystems')
    # ### end Alembic commands ###
